version: '3.7'

services:
  db:
    image: 'postgres:12'
    environment: 
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - /root/atrin-cicd/dreamon-v0/database/postgres_data:/var/lib/postgresql/data
      - ./back/PG/DOM_DB.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PGHOST=db
        - PGUSER=postgres
        - PGPASSWORD=
        - PGDATABASE=DOM
        - PGPORT=5432
        - SECRET=1234ThisIsABadIdeaDontTryThisAtHome
    environment:
      - "PGHOST=db"
      - "PGUSER=postgres"
      - "PGPASSWORD="
      - "PGDATABASE=DOM"
      - "PGPORT=5432"
      - "SECRET=1234ThisIsABadIdeaDontTryThisAtHome"
    command: npm start
    ports:
      - 127.0.0.1:8075:8080
    depends_on:
      - db
