name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_and_deploy_docker:

    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v2
    - name: Remove previous instances    
      env:
        PG_DATA: /root/atrin-cicd/dreamon-v0/database/postgres_data
      run: |
        docker-compose down
        docker-compose stop
        docker-compose rm -f

    - name: Build the Docker image
      env:
        PG_DATA: /root/atrin-cicd/dreamon-v0/database/postgres_data
      run: docker-compose build --pull --force-rm
    - name: Deploy
      env:
        PG_DATA: /root/atrin-cicd/dreamon-v0/database/postgres_data
      run: docker-compose up -d
