name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: VPSAtrinMahdiGermany

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build --pull --force-rm
    - name: Deploy
      run: docker-compose up -d
