name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_and_deploy_docker:

    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build --pull
    - name: Deploy
      run: docker-compose up -d
